CREATE TABLE IF NOT EXISTS services (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    price_base DECIMAL(10,2) NOT NULL,
    price_unit VARCHAR(20),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
